# Generated by Django 6.0.4 on 2026-05-04 14:13

import django.core.validators
import django.db.models.deletion
import index.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='index.comments')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=30)),
                ('desciption', models.CharField()),
                ('image', models.FileField(upload_to=index.models.uploaded_image, validators=[django.core.validators.FileExtensionValidator(['jpeg', 'png', 'jpg', 'webp', 'gif'])])),
                ('post_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-post_date'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=67)),
                ('birthday', models.DateField()),
                ('hobby', models.CharField(max_length=67)),
                ('quote', models.TextField(blank=True, null=True)),
                ('pfp', models.FileField(blank=True, null=True, upload_to=index.models.uploaded_pfp, validators=[django.core.validators.FileExtensionValidator(['jpeg', 'png', 'jpg', 'webp'])])),
                ('join_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-join_date'],
            },
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postmadecomment', to='index.post'),
        ),
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postmadetopic', to='index.topic'),
        ),
        migrations.AddField(
            model_name='topic',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topicsmade', to='index.user'),
        ),
        migrations.AddField(
            model_name='post',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postsmadeuser', to='index.user'),
        ),
        migrations.AddField(
            model_name='comments',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usermadecomment', to='index.user'),
        ),
    ]
