# Generated by Django 6.0.5 on 2026-05-31 06:14

import django.core.validators
import index.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_rename_desciption_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=index.models.uploaded_image, validators=[django.core.validators.FileExtensionValidator(['jpeg', 'png', 'jpg', 'webp', 'gif'])]),
        ),
    ]
