# Generated by Django 6.0.4 on 2026-05-15 13:14

import django.core.validators
import django.db.models.deletion
import index.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_comments_post_topic_user_delete_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=67)),
                ('birthday', models.DateField()),
                ('hobby', models.CharField(blank=True, max_length=67, null=True)),
                ('quote', models.TextField(blank=True, null=True)),
                ('pfp', models.FileField(blank=True, null=True, upload_to=index.models.uploaded_pfp, validators=[django.core.validators.FileExtensionValidator(['jpeg', 'png', 'jpg', 'webp'])])),
                ('join_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-join_date'],
            },
        ),
        migrations.AlterField(
            model_name='comments',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usermadecomment', to='index.userprofile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postsmadeuser', to='index.userprofile'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topicsmade', to='index.userprofile'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
