# Generated by Django 6.0.4 on 2026-06-05 02:46

import django.core.validators
import index.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_alter_userprofile_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pfp',
            field=models.FileField(blank=True, null=True, upload_to=index.models.uploaded_pfp, validators=[django.core.validators.FileExtensionValidator(['jpeg', 'png', 'jpg', 'webp', 'gif'])]),
        ),
    ]
